# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_date', models.DateField(verbose_name='\u8bf7\u5047\u65f6\u671f')),
                ('detail', models.CharField(max_length=20, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='tel',
        ),
        migrations.AddField(
            model_name='attendance',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workManage.Worker', verbose_name='\u5de5\u4eba'),
        ),
    ]
