# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workManage', '0002_auto_20170422_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_date', models.DateField(verbose_name='\u8bf7\u5047\u65f6\u671f')),
                ('detail', models.CharField(max_length=20, verbose_name='\u5907\u6ce8')),
                ('money', models.IntegerField(verbose_name='\u5de5\u8d44')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workManage.Worker', verbose_name='\u5de5\u4eba')),
            ],
        ),
    ]
