# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workManage', '0003_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField(verbose_name='\u603b\u4ef7')),
                ('changeDate', models.DateField(verbose_name='\u56de\u6b3e\u65e5\u671f')),
                ('detail', models.CharField(max_length=20, verbose_name='\u5907\u6ce8')),
                ('type', models.CharField(max_length=5, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('type_change', models.CharField(max_length=5, verbose_name='\u4ea4\u6613\u65b9\u5f0f')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workManage.Company', verbose_name='\u516c\u53f8')),
            ],
        ),
    ]
